word_lists = {"ezinaulo": {
    "Ezi N\'Ulọ": "Family",
    "Nna": "Father",
    "Nne": "Mother",
    "Nwoke": "Man/Male",
    "Nwaanyị": "Woman/Female",
    "Di": "Husband",
    "Nwunye": "Wife",

    "Nwa": "Child/Baby",
    "Nwata": "Child",
    "Nwantakịrị": "Little child",
    "Nwa Nwa": "Grandchild",
    "Nwa Nwoke": "Male Child",
    "Nwa Nwaanyị": "Female Child",
    "Ụmụ": "Children",
    "Ụmụaka": "Children",
    "Ụmụntakịrị": "Little children",
    "Ụmụ Ụmụ": "Grandchildren",
    "Ụmụ ejima": "Twins",

    "Nwanne": "Sibling",
    "Ụmụnne": "Siblings",
    "Nwanne Nwoke": "Brother",
    "Nwanne Nwaanyị": "Sister",
    "Ada": "First daughter",
    "Ọkpara": "First Son",

    "Nna Ochie": "Grandfather",
    "Nne Ochie": "Grandmother",
    "Nna Nna": "Father’s Father",
    "Nne Nna": "Father’s Mother",
    "Nne Nne": "Mother’s Mother",
    "Nna Nne": "Mother’s Father",

    "Okoro": "Adult Male",
    "Okorobịa": "Adult Male",
    "Agbọghọ": "Adult female",
    "Agbọghọbịa": "Adult female",
    "Dada": "Aunt",
    "Dede": "Uncle",
    "Nwanne Nna": "Paternal Aunt or Uncle",
    "Nwanne Nne": "Maternal Aunt or Uncle",
    "Ụmụnne Nna": "Paternal Aunts and Uncles",
    "Ụmụnne Nne": "Maternal Aunts and Uncles",

    "Nwa Nwanne Nne": "Maternal Cousin",
    "Nwa Nwanne Nna": "Paternal Cousin",
    "Nwa Nwanne": "Nephew or Niece",
    "Nwa nwoke Nwanne": "Nephew",
    "Nwa Nwaanyị Nwanne": "Niece",
    "Ụmụ Ụmụnne": "Nephews and Nieces",

    "Ikwunne": "Mother’s Kindred",
    "Ikwunna": "Father’s Kindred",
    "Nwanna": "Kinsman (extended family)",
    "Ụmụnna": "Kinsmen",
    "ỤmụAda": "Women kin council",
    "Ibenna": "Paternal relatives (father’s side)",
    "Ibenne": "Maternal relatives (mother’s side)",
    "Ala Nna": "Father’s Land (Father Kindred)",
    "Ala Nnem": "Mother’s Land",
    "Ikwu Nne": "Mother’s Land (Mothers Kindred)",

    "Ọgọ": "In-law",
    "Nne Di": "Mother-in-law",
    "Nne nwunye": "Mother-in-law",
    "Nna Di": "Father-in-law",
    "Nna nwunye": "Father-in-law",

    "Ndị Ikom": "Men folk",
    "Ndị Inyom": "Women Folk"
},
'akụkụ_ahụ': {
    "Àhụ niile": "Whole body",
    "Ísí": "Head",
    "Ntùtù ísi": "Hair",
    "Ányá": "Eye",
    "Ọnụ": "Mouth",

    "Íré": "Tongue",
    "Ézé": "Teeth",
    "Ntị": "Ear",
    "Nkù ányà": "Eye brow",
    "Nchì": "Cheek",

    "Ólú": "Neck",
    "Àgbà": "Jaw",
    "Ímí": "Nose",
    "Égbùgbèrè ọnụ": "Lips",
    "Íhú": "Face",

    "Óbì": "Chest",
    "Árá": "Breast",
    "Àzụ": "Back",
    "Áfọ": "Belly",
    "Ótùbò": "Navel",
    "Áká": "Hand",

    "Ùbú ákã": "Shoulder",
    "Íkpèrè ákã": "Elbow",
    "Mkpịsị ákã": "Fingers",
    "Mbọ ákã": "Finger nails",
    "Ísí ákã": "Thumb",
    "Úkwù": "Waist",

    "Ụkwụ": "Leg",
    "Íkpèrè ụkwụ": "Knee",
    "Mkpịsị ụkwụ": "Toes",
    "Mbọ ụkwụ": "Toenails",

    "Lee": "See",
    "Metụ": "Touch",
    "Gosi": "Show",
    "Hụrụ": "Saw"
},
'ahụike': {
    "Agụụ": "Hunger",
    "Ọrịa": "Illness",
    "Àhú ike": "Good health",
    "Ụfụ": "Pain/Irritation",
    "Ọkọ": "Itch",

    "Ọnyá": "Sore",
    "Ọnyá Akpịrị": "Sore throat",
    "Anya mgbu": "Eye pain",
    "Nti mgbu": "Ear pain",

    "Isi ọwụwa": "Headache",
    "Íké ọgwụgwụ": "Fatigue/Tireness",
    "Ahụ Mgbu": "Body pain/body ache",
    "Úkwu mgbu": "Waist pain",
    "Azụ Mgbu": "Back pain",

    "Afọ ọrụrụ": "Belly ache",
    "Afọ ọsịsa": "Diarrhea",
    "Ajụ": "Dizziness",
    "Agbọ": "Nausea",
    "Óyi": "Cold",

    "Ịba": "Fever",
    "Ótuto": "Boil",
    "Ọbara": "Blood",
    "Ụkwara": "Cough",
    "Azụzụ": "Flu",

    # Sample Expressions (Kept EXACTLY as in PDF)
    "Agụụ na-agụ m": "I am hungry",
    "Ọ dị ka a chọrọ m ị da ọrịa": "It seems i am falling ill.",
    "Àhú siri m ike": "I feel well",
    "Àhú esirịrị m ike": "I don't feel well",
    "Àhú a dighị m": "I am ill",
    "Anya na-afụ m ụfụ": "My eyes hurt",

    "Ọkọ na-akọ m n’azụ": "My back itches",
    "Ahụm niile na-akọ m ọkọ": "My whole body itches",
    "Ọnyá dị m n’ụkwụ na-afụ m ezigbo ụfụ": "The sore on my leg really hurts me.",
    "E nwere m Ọnyá Akpịrị": "I have Sore throat",
    "Ụkwara na-akwa m": "I have cough",
    "E nwere m azụzụ": "I have flu",
    "E nwere m isi ọwụwa": "I have a headache/ My head aches",
    "Isi na-awa m": "I have headache",
    "Íké gwụrụ m": "I am tired",
    "Ahụ na- egbu m mgbu": "My  body aches",
    "Úkwu na-egbu m mgbu": "I have waist pain",
    "Azụ na-egbu m mgbu": "My back aches",
    "E nwere m anya mgbu": "I have eye pain",
    "Nti na-egbu m mgbu": "My ear hurts",
    "Afọ na-arụ m": "I have a stomach ache",

    "Afọ na-asa m": "I have diarrhea",
    "Ajụ na-ebe m": "I feel dizzy",
    "Ọ na-eme m agbọ": "I feel nausea",
    "Óyi na-atụ m": "I feel cold",
    "O nwere ịba": "He/she has a fever",
    "Ọbara na-agba ya n’ụkwụ": "She/He is bleeding on the leg.",

    # Questions
    "Gịnị na-eme gị?": "What is wrong with you?",
    "Isi ọ na-awa gị?": "Does your head ache?",

    "Ndo": "Sorry",
    "Ka anyị gaa ụlọọgwụ": "Let’s go to the hospital.",
    "Ị ṅụgo ọgwụ gị": "Have you taken your medication?"
},
'anụmanụ': {
    "mgbada": "antelope",
    "ụsụ": "bat",
    "nnụnụ": "bird",
    "nwamba": "cat",
    "ọkụkọ": "chicken",

    "ehi": "cow",
    "efi": "cattle",
    "nshikọ": "crab",
    "nkịta": "dog",
    "ịnyịnya ibu": "donkey/mule",
    "ọbọgwụ": "duck",

    "ugo": "eagle",
    "enyi": "elephant",
    "azụ": "fish",
    "agwọ": "snake",
    "ewu": "goat",
    "ọkwa": "goose",

    "ịnyịnya": "horse",
    "nwa atụrụ": "lamb",
    "agụ": "leopard/tiger",
    "ọdụm": "lion",
    "ngwere": "lizard",
    "enwe": "monkey",
    "oke": "mouse/rat",
    "ikwikwii": "owl",

    "ezi": "pig",
    "ndụlị": "pigeon",
    "nwa ịnyịnya": "pony",
    "oke ụlọ": "rabbit",
    "oke ọkụkọ": "rooster",
    "atụrụ": "sheep",
    "akpị": "scorpion",
    "eju": "snail",

    "nza": "sparrow",
    "ọsa": "squirrel",
    "mbe": "tortoise",
    "torotoro": "turkey",
    "udele": "vulture",

    "ụlọ anụmanụ": "zoo"
}}